### ISSUE TITLE
Can't able to install on MacOS High Sierra

### ISSUE THREAD

**Issue by karthick-nagendran** [imkira/mobiledevice#16]
Unable to install mobiledevice on MacOS High Sierra
When I run the command `brew install mobiledevice` I got the following error message 

fatal: Not a git repository (or any of the parent directories): .git
clang -Wall -fobjc-arc -o mobiledevice -framework CoreFoundation -framework Cocoa -framework MobileDevice -F/System/Library/PrivateFrameworks -DMOBILEDEVICE_CLI_VERSION=\"2.0.0\" -DMOBILEDEVICE_CLI_REVISION=\"\" cli.m commands.m device.m get_app_prop.m get_bundle_id.m get_device_prop.m help.m install_app.m invalid_usage.m list_app_props.m list_apps.m list_device_props.m list_devices.m tunnel.m uninstall_app.m version.m
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mobiledevice] Error 1

**Comment by Vigneshh** [comment]
I am also facing issue in installing mobiledevice on MacOS High Sierra 10.13.2

Got below error message when running the command "brew install mobiledevice"

mobiledevice: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

**Comment by ChristopherDrum** [comment]
Yep, I'm in the same boat. Can't install via `brew install mobiledevice`

**Comment by DomT4** [comment]
The project seems pretty dead but I've submitted a fix in https://github.com/imkira/mobiledevice/pull/20. I'll fix things on the Homebrew side as well.

**Comment by DomT4** [comment]
Homebrew-based installation should be fixed now.
